- name: install Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: maven clean pacakage
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: Rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Install MySQL client
  ansible.builtin.yum:
    name: mysql
    state: present

    # - name: copy schema.sql to shipping.sql
#   ansible.builtin.command: cp /app/db/schema.sql /app/schema/shipping.sql

- name: load mysql schema my self cp schema to shipping
  ansible.builtin.shell: mysql -h mysql.munidevops.shop -uroot -pRoboShop@1 < /app/schema/{{component}}.sql 

- name: Start Application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup
